FROM ubuntu:18.04

MAINTAINER David Brown

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7 python3-pip

ENV SRC=app
ENV SRVHOME=/srv
ENV SRVPROJ=$SRVHOME/$SRC

COPY $SRC $SRVPROJ

RUN pip3 install -r $SRVPROJ/requirements.txt

EXPOSE 8000

WORKDIR $SRVPROJ

STOPSIGNAL SIGINT
ENTRYPOINT ["/bin/bash", "run.sh"]
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]