FROM ubuntu:18.04

MAINTAINER David Brown

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7 python3-pip

ENV SRC=app
ENV SRVHOME=/srv
ENV SRVPROJ=$SRVHOME/$SRC

COPY $SRC/requirements.txt $SRVHOME/requirements.txt
RUN pip3 install -r $SRVHOME/requirements.txt

EXPOSE 8000

WORKDIR $SRVPROJ

STOPSIGNAL SIGINT
ENTRYPOINT ["python3", "manage.py"]
CMD ["runserver", "0.0.0.0:8000"]